### ISSUE TITLE
Feature req: save(share) as Libpcap File Format / proper handling websocket

### ISSUE THREAD

**Issue by AndCycle** [huolizhuminh/NetWorkPacketCapture#13]
just download the free version and done some simple test on this app,
which work nicely,

unfortunately it missing some important feature

1. been able to save raw data for further analysis
share function save parsed txt document which result in broken raw binary data,
been able to do further analysis is crucial for this kind of tool

2. proper handling websocket
as websocket is getting popular for realtime control to cut the latency,
it's not able to proper parse websocket.

**Comment by huolizhuminh** [comment]
The first feature had been developed in the pro version provided in google play.The Second feature will be developed in the feature.Anyway thank for your advice.

**Comment by AndCycle** [comment]
so the first feature is in pro version? 
you can just add a dummy button to imply that exists in pro version so people will know it's a paid feature :p

looking forward for the websocket support
