### ISSUE TITLE
为什么需要 TcpProxyServer？

### ISSUE THREAD

**Issue by CrazyBoyFeng** [huolizhuminh/NetWorkPacketCapture#46]
从 tun 接口 `read()` 的 tcp 数据包，改改包头通过 `protect()` 通道发给 wan 不就可以了？  
为什么需要起一个 `TcpProxyServer` ？  
https://github.com/huolizhuminh/NetWorkPacketCapture/blob/88e1a1accb5c865ea525f89b10f3d9503b8628be/vpnadaptercore/src/main/java/com/minhui/vpn/service/FirewallVpnService.java#L369

**Comment by CrazyBoyFeng** [comment]
看明白了，这是个 fake server。  

从 tun 收到的 packet 是一个一个的数据碎片，不是应用层的 socket 流。手动组装成 socket 比较困难。要处理序号、重复包、残包、握手、挥手细节。  
而 fake server 是 packet 和 socket 的桥梁。app 把 tun 收到的 packet 的目的 ip 和端口改成 fake server 的 ip 和端口，并记录原始目的 ip 和端口，然后写回到 tun，然后就能在 jvm 上的 fake server 里收到客户端的连接请求。再开启到原始目的 ip 和端口的连接，把 IO 流对上去。

**Comment by wustwg** [comment]
> 看明白了，这是个 fake server。
> 
> 从 tun 收到的 packet 是一个一个的数据碎片，不是应用层的 socket 流。手动组装成 socket 比较困难。要处理序号、重复包、残包、握手、挥手细节。
> 而 fake server 是 packet 和 socket 的桥梁。app 把 tun 收到的 packet 的目的 ip 和端口改成 fake server 的 ip 和端口，并记录原始目的 ip 和端口，然后写回到 tun，然后就能在 jvm 上的 fake server 里收到客户端的连接请求。再开启到原始目的 ip 和端口的连接，把 IO 流对上去。

老哥  牛逼呀 这都让你分析出来了。
听你这么一解释 作者这种思路还挺巧妙的呢，好聪明。

**Comment by wustwg** [comment]
> 看明白了，这是个 fake server。
> 
> 从 tun 收到的 packet 是一个一个的数据碎片，不是应用层的 socket 流。手动组装成 socket 比较困难。要处理序号、重复包、残包、握手、挥手细节。
> 而 fake server 是 packet 和 socket 的桥梁。app 把 tun 收到的 packet 的目的 ip 和端口改成 fake server 的 ip 和端口，并记录原始目的 ip 和端口，然后写回到 tun，然后就能在 jvm 上的 fake server 里收到客户端的连接请求。再开启到原始目的 ip 和端口的连接，把 IO 流对上去。

你的意思是  比如发给a的数据包 源IP-B（虚拟IP）端口PC，将目的ip-A 端口PA改成  虚拟ip-B 端口PB ，也就是fakeserver，写回虚拟网卡
接着在fakeserver这里，就收到了 新连接，accept新连接之后，根据源ip 端口PC找到对应的目标ip-A 端口PA，接着fakeserver 连接目标ip-A 端口PA， 再将tcp数据流转发到目标服务器。

我很好奇作者这思路怎么想到的。。。这比lwip的方式巧妙多了，也更简单，不用考虑ip协议栈的问题。

**Comment by CrazyBoyFeng** [comment]
对就是这个原理。这叫做：二次 NAT。

第一次 NAT 是把目标换成 `TcpProxyServer`，第二次 NAT 是从 `TcpProxyServer` 连接原始目标服务器。

这个写法我在 SmartProxy、BaoLianDeng 等好几处都见过，不知道是谁最早想出来的。
